%%VALORES DE X
x=[100 1000 1500 3000 4000 5000 6000];
 
%%VALORES DE Y = F(x)
y=[50 100 200 300 500 700 900];

%%OBTENER UN POLINOMIO QUE SE AJUSTE A LOS PUNTOS X Y Y
n=2; 				%%GRADO DEL POLINOMIO DE AJUSTE
p=polyfit(x,y,n)	%%FUNCION QUE REALIZA EL AJUSTE POLINOMIAL

%%DONDE SE COMPARA LA CURVA AJUSTADA CONTRA LOS 
%%VALORES EXPERIMENTALES
xi=linspace(0,10000,60000);	%%ESPACIO DE PUNTOS PARA Xi
z=polyval(p,xi);				%%EVALUACION DEL POLINOMIO P EN EL ESPACIO Xi

%%SE CREA UN ESPACIO PARA REALIZAR UNA GRAFICA EN 
%%SE REALIZA LA FIGURA CORRESPONDIENTE
figure(1);
plot(x,y,'o',xi,z,'-'),grid;
    ylabel('F(Y)');
    xlabel('X');
title('Ajuste de minimos cuadrados');