tiempo.o: tiempo.c
	gcc tiempo.c -c -Wall

shell-sort.o: shell-sort.c
	gcc shell-sort.c -c -Wall

compile: shell-sort.o tiempo.o
	gcc shell-sort.o tiempo.o

100:
	./a.out < ../../numbers/100.txt

1k:
	./a.out < ../../numbers/1k.txt

5k:
	./a.out < ../../numbers/5k.txt

10k:
	./a.out < ../../numbers/10k.txt


50k:
	./a.out < ../../numbers/50k.txt

200k:
	./a.out < ../../numbers/200k.txt

400k:
	./a.out < ../../numbers/400k.txt

500k:
	./a.out < ../../numbers/500k.txt

600k:
	./a.out < ../../numbers/600k.txt


800k:
	./a.out < ../../numbers/800k.txt

1m:
	./a.out < ../../numbers/1m.txt

2m:
	./a.out < ../../numbers/2m.txt

3m:
	./a.out < ../../numbers/3m.txt

4m:
	./a.out < ../../numbers/4m.txt

5m:
	./a.out < ../../numbers/5m.txt

6m:
	./a.out < ../../numbers/6m.txt

7m:
	./a.out < ../../numbers/7m.txt

8m:
	./a.out < ../../numbers/8m.txt

9m:
	./a.out < ../../numbers/9m.txt

10m:
	./a.out < ../../numbers/10m.txt	

clean:
	rm -f *.o a.out